### ISSUE TITLE
Unable to equip Armour on PCs

### ISSUE THREAD

**Issue by PeterJMitchell71** [Genii-Locorum/Rivers-of-London#1]
Unable to put regular armour on a character during creation, error message shows "Unable to meet pre-requisites for Regular Armour"
FVTT version 11.308
RoL version 0.1.10
![image](https://github.com/Genii-Locorum/rol/assets/87539950/6376e1e2-6997-43aa-a68e-b621b6d7396a)

Modules in use
![image](https://github.com/Genii-Locorum/rol/assets/87539950/7ea6b4da-0314-47d4-b29c-cd49be6c2f5d)

**Comment by Genii-Locorum** [comment]
Thanks for the report - this has (fingers crossed) been fixed in V11 which I've just released.
